In [1]:
import numpy as np
one = np.array([1,2,3,4])
print(one)

[1 2 3 4]


In [2]:
pip list


Package                   Version
------------------------- ---------------
altair                    5.5.0
annotated-types           0.7.0
anyio                     4.9.0
argon2-cffi               25.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
audioop-lts               0.2.2
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
blinker                   1.9.0
cachetools                5.5.2
certifi                   2025.7.14
cffi                      1.17.1
charset-normalizer        3.4.2
click                     8.2.1
cohere                    5.17.0
colorama                  0.4.6
comm                      0.2.2
comtypes                  1.4.12
contourpy                 1.3.2
cycler                    0.12.1
debugpy                   1.8.15
decorator                 5.2.1
defusedxml                0.7.1
distlib       

In [5]:
two = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(two[0,1])

2


In [23]:
print(two[2,1])

8


In [27]:
reshaped_array = one.reshape(4,1)
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]]


In [28]:
A =np.array([1,2,3])
B =np.array([1,2,3])
c= A+B
print(c)

[2 4 6]


In [29]:
D =A*B
print(D)

[1 4 9]


In [30]:
dot_product = np.dot(A,B)
print(dot_product)

14


In [42]:
E= np.array([[1,2,3], [4,5,7],[3,4,6]])
F = np.array([[2,3,4],[6,3,6],[1,2,3]])
G = E*F
print(G)

[[ 2  6 12]
 [24 15 42]
 [ 3  8 18]]


In [43]:
H = np.dot(E,F)
print(H)

[[17 15 25]
 [45 41 67]
 [36 33 54]]


In [44]:
data = np.array([1,2,3,4,5,6])
#mean
mean = np.mean(data)
print(mean)

3.5


In [45]:
median = np.median(data)
print(median)

3.5


In [46]:
#Standard dev
std_dev = np.std(data)
print(std_dev)

1.707825127659933
